[phases.setup]
nixPkgs = ["python311Full", "gcc", "libffi", "libffi.dev", "openssl", "openssl.dev"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmds = ["python3 bot.py"]
